repos:
- repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
  rev: v1.0
  hooks:
  - id: sops-encryption
- repo: https://github.com/nix-community/nixpkgs-fmt
  rev: master
  hooks:
  - id: nixpkgs-fmt